[package]
name = "tts-loop"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flite = { path = "../flite" }
deepspeech = "0.9.0"
rodio = "0.14"
thiserror = "1.0.30"
