[package]
name = "deepspeech-sys"
description = "Bindgen output for the DeepSpeech C++ API"
license = "MPL-2.0"
documentation = "https://docs.rs/deepspeech-sys"
repository = "https://github.com/RustAudio/deepspeech-rs"
version = "0.9.0"

[build-dependencies]
cc = "1.0"
bindgen = "0.59"

